In [98]:
import pandas as pd

df = pd.read_csv('academy_awards.csv', encoding='ISO-8859-1')

df.head()

,Year,Category,Nominee,Additional Info,Won?,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,2010 (83rd),Actor -- Leading Role,Javier Bardem,Biutiful {'Uxbal'},NO,NaN,NaN,NaN,NaN,NaN,NaN
1,2010 (83rd),Actor -- Leading Role,Jeff Bridges,True Grit {'Rooster Cogburn'},NO,NaN,NaN,NaN,NaN,NaN,NaN
2,2010 (83rd),Actor -- Leading Role,Jesse Eisenberg,The Social Network {'Mark Zuckerberg'},NO,NaN,NaN,NaN,NaN,NaN,NaN
3,2010 (83rd),Actor -- Leading Role,Colin Firth,The King's Speech {'King George VI'},YES,NaN,NaN,NaN,NaN,NaN,NaN
4,2010 (83rd),Actor -- Leading Role,James Franco,127 Hours {'Aron Ralston'},NO,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
# checking out the unnamed columns
last_six_columns = df.iloc[:, 5:11]
last_six_columns.head()

for i in range(5,11):
    print(df.iloc[:, i].value_counts())

*                                                                                                               7
 discoverer of stars                                                                                            1
 resilience                                                                                                     1
 D.B. "Don" Keele and Mark E. Engebretson has resulted in the over 20-year dominance of constant-directivity    1
 error-prone measurements on sets. [Digital Imaging Technology]"                                                1
Name: Unnamed: 5, dtype: int64
*                                                                   9
 sympathetic                                                        1
 direct radiator bass style cinema loudspeaker systems. [Sound]"    1
 flexibility and water resistance                                   1
Name: Unnamed: 6, dtype: int64
*                                                     1
 kindly                                               1
 while requiring no dangerous solvents. [Systems]"    1
Name: Unnamed: 7, dtype: int64
*                                                 1
 understanding comedy genius - Mack Sennett.""    1
Name: Unnamed: 8, dtype: int64
*    1
Name: Unnamed: 9, dtype: int64
*    1
Name: Unnamed: 10, dtype: int64

In [100]:
# the 'Additional Info' column contains a few different formatting styles
df.loc[:, 'Additional Info'].value_counts()

Metro-Goldwyn-Mayer                                                                 60
Walt Disney, Producer                                                               57
Warner Bros.                                                                        42
John Williams                                                                       37
France                                                                              35
Alfred Newman                                                                       34
Italy                                                                               26
Paramount                                                                           24
Gordon Hollingshead, Producer                                                       22
Edith Head                                                                          22
RKO Radio                                                                           20
20th Century-Fox                                                                    20
Spain                                                                               19
Victor Young                                                                        19
Leon Shamroy                                                                        17
Woody Allen                                                                         16
Max Steiner                                                                         16
Jerry Goldsmith                                                                     16
Metro-Goldwyn-Mayer Studio Sound Department, Douglas Shearer, Sound Director        15
Alex North                                                                          14
Miklos Rozsa                                                                        14
Sweden                                                                              14
Columbia                                                                            13
Dimitri Tiomkin                                                                     13
Pete Smith, Producer                                                                13
Columbia Studio Sound Department, John Livadary, Sound Director                     13
Jean Louis                                                                          12
William Wyler                                                                       12
Franz Waxman                                                                        12
Music and Lyric by Randy Newman                                                     12
                                                                                    ..
Herbert Stothart, Bronislau Kaper                                                    1
Alejandro González Iñárritu                                                          1
Stephen Mirrione                                                                     1
Being Julia {'Julia Lambert'}                                                        1
The China Syndrome {'Kimberly Wells'}                                                1
John Cameron                                                                         1
James Poe, John Farrow, S.J. Perelman                                                1
Music by Frank Churchill; Lyrics by Ned Washington                                   1
Dan Gifford, William Gazecki                                                         1
Written by John Logan                                                                1
John Lasseter                                                                        1
Greg Cannom, Ve Neill, Yolanda Toussieng                                             1
Marcel Grignon                                                                       1
Art Direction: Alexander Golitzen, Joseph Wright; Set Decoration: Howard Bristol     1
Music by Sting and David Hartley; Lyric by Sting                                     1
Primrose Path {'Mamie Adams'}                                                        1
The Dresser {'Sir'}                                                                  1
Jean Marsan, Henry Troyat, Jacques Perret, Henri Verneuil, Raoul Ploquin             1
Music by John Kander; Lyric by Fred Ebb                                              1
Boogie Nights {'Jack Horner'}                                                        1
The Spiral Staircase {'Mrs. Warren'}                                                 1
Paul Franklin, Chris Corbould, Andrew Lockley and Peter Bebb                         1
Stefen Fangmeier, John Frazier, Habib Zargarpour, Henry La Bounta                    1
Kazakhstan                                                                           1
The Diary of Anne Frank {'Mr. Dussell'}                                              1
John Taylor, Leon Clore and Grahame Tharp, Producers                                 1
Charles Walters                                                                      1
Driving Miss Daisy {'Daisy Werthan'}                                                 1
John Nelson, Neil Corbould, Tim Burke, Rob Harvey                                    1
Tim Robbins                                                                          1
Name: Additional Info, dtype: int64

In [101]:
# Reduce 'Year' to just the year
df['Year'] = df['Year'].str[0:4]
print(df.loc[1:3, :])
print(df.describe())
print(df.dtypes)

   Year               Category          Nominee  \
1  2010  Actor -- Leading Role     Jeff Bridges
2  2010  Actor -- Leading Role  Jesse Eisenberg
3  2010  Actor -- Leading Role      Colin Firth

                          Additional Info Won? Unnamed: 5 Unnamed: 6  \
1           True Grit {'Rooster Cogburn'}   NO        NaN        NaN
2  The Social Network {'Mark Zuckerberg'}   NO        NaN        NaN
3    The King's Speech {'King George VI'}  YES        NaN        NaN

  Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10
1        NaN        NaN        NaN         NaN
2        NaN        NaN        NaN         NaN
3        NaN        NaN        NaN         NaN
         Year Category       Nominee      Additional Info   Won? Unnamed: 5  \
count   10137    10137         10137                 9011  10137         11
unique     83       40          6001                 6424     16          5
top      1941  Writing  Meryl Streep  Metro-Goldwyn-Mayer     NO          *
freq      192      888            16                   60   7168          7

       Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10
count          12          3          2          1           1
unique          4          3          2          1           1
top             *          *          *          *           *
freq            9          1          1          1           1
Year               object
Category           object
Nominee            object
Additional Info    object
Won?               object
Unnamed: 5         object
Unnamed: 6         object
Unnamed: 7         object
Unnamed: 8         object
Unnamed: 9         object
Unnamed: 10        object
dtype: object

In [102]:
df['Year'] = df['Year'].astype('int64')
df.dtypes

Year                int64
Category           object
Nominee            object
Additional Info    object
Won?               object
Unnamed: 5         object
Unnamed: 6         object
Unnamed: 7         object
Unnamed: 8         object
Unnamed: 9         object
Unnamed: 10        object
dtype: object

In [103]:
# choose years after 2000
later_than_2000 = df[(df['Year'] > 2000)]
print((df['Year'] > 2000).head())
later_than_2000.iloc[19:25, :]

0    True
1    True
2    True
3    True
4    True
Name: Year, dtype: bool

,Year,Category,Nominee,Additional Info,Won?,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
19,2010,Actress -- Supporting Role,Jacki Weaver,Animal Kingdom {'Janine 'Smurf' Cody'},NO,NaN,NaN,NaN,NaN,NaN,NaN
20,2010,Animated Feature Film,How to Train Your Dragon,Chris Sanders and Dean DeBlois,NO,NaN,NaN,NaN,NaN,NaN,NaN
21,2010,Animated Feature Film,The Illusionist,Sylvain Chomet,NO,NaN,NaN,NaN,NaN,NaN,NaN
22,2010,Animated Feature Film,Toy Story 3,Lee Unkrich,YES,NaN,NaN,NaN,NaN,NaN,NaN
23,2010,Art Direction,Alice in Wonderland,Production Design: Robert Stromberg; Set Decor...,YES,NaN,NaN,NaN,NaN,NaN,NaN
24,2010,Art Direction,Harry Potter and the Deathly Hallows Part 1,Production Design: Stuart Craig; Set Decoratio...,NO,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
# Conditionally filter to choose only categories in 'award_categories'
# equivalent to ticking those boxes in Excel's filter dropdown
award_categories = ['Actor -- Leading Role'
                    , 'Actor -- Supporting Role' 
                    , 'Actress -- Leading Role'
                    , 'Actress -- Supporting Role']
nom_bool_vec = later_than_2000['Category'].isin(award_categories)
print(nom_bool_vec.head())
nominations = later_than_2000[nom_bool_vec]
nominations.iloc[19:25, :]

0    True
1    True
2    True
3    True
4    True
Name: Category, dtype: bool

,Year,Category,Nominee,Additional Info,Won?,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
19,2010,Actress -- Supporting Role,Jacki Weaver,Animal Kingdom {'Janine 'Smurf' Cody'},NO,NaN,NaN,NaN,NaN,NaN,NaN
135,2009,Actor -- Leading Role,Jeff Bridges,Crazy Heart {'Bad Blake'},YES,NaN,NaN,NaN,NaN,NaN,NaN
136,2009,Actor -- Leading Role,George Clooney,Up in the Air {'Ryan Bingham'},NO,NaN,NaN,NaN,NaN,NaN,NaN
137,2009,Actor -- Leading Role,Colin Firth,A Single Man {'George'},NO,NaN,NaN,NaN,NaN,NaN,NaN
138,2009,Actor -- Leading Role,Morgan Freeman,Invictus {'Nelson Mandela'},NO,NaN,NaN,NaN,NaN,NaN,NaN
139,2009,Actor -- Leading Role,Jeremy Renner,The Hurt Locker {'Staff Sergeant William James'},NO,NaN,NaN,NaN,NaN,NaN,NaN

In [105]:
# 'map' NO -> 0, YES -> 1 in the 'Won?' column
replace_dict = {'NO': 0, 'YES': 1}
# false positive SettingWithCopyWarning
pd.options.mode.chained_assignment = None  # default='warn'
nominations.loc[:,'Won'] = nominations.loc[:,'Won?'].map(replace_dict)
nominations.loc[:,['Won', 'Won?']].head()

   Won Won?
0    0   NO
1    0   NO
2    0   NO
3    1  YES
4    0   NO

In [106]:
columns_to_drop = ['Won?'
                   , 'Unnamed: 5'
                   , 'Unnamed: 6'
                   , 'Unnamed: 7'
                   , 'Unnamed: 8'
                   , 'Unnamed: 9'
                   , 'Unnamed: 10' ]
final_nominations = nominations.drop(columns_to_drop, axis=1)
print(final_nominations.iloc[19:25, :])
final_nominations = final_nominations.reset_index(drop=True)
print(final_nominations.iloc[19:25, :])
final_nominations.head()

     Year                    Category         Nominee  \
19   2010  Actress -- Supporting Role    Jacki Weaver
135  2009       Actor -- Leading Role    Jeff Bridges
136  2009       Actor -- Leading Role  George Clooney
137  2009       Actor -- Leading Role     Colin Firth
138  2009       Actor -- Leading Role  Morgan Freeman
139  2009       Actor -- Leading Role   Jeremy Renner

                                      Additional Info  Won
19             Animal Kingdom {'Janine 'Smurf' Cody'}    0
135                         Crazy Heart {'Bad Blake'}    1
136                    Up in the Air {'Ryan Bingham'}    0
137                           A Single Man {'George'}    0
138                       Invictus {'Nelson Mandela'}    0
139  The Hurt Locker {'Staff Sergeant William James'}    0
    Year                    Category         Nominee  \
19  2010  Actress -- Supporting Role    Jacki Weaver
20  2009       Actor -- Leading Role    Jeff Bridges
21  2009       Actor -- Leading Role  George Clooney
22  2009       Actor -- Leading Role     Colin Firth
23  2009       Actor -- Leading Role  Morgan Freeman
24  2009       Actor -- Leading Role   Jeremy Renner

                                     Additional Info  Won
19            Animal Kingdom {'Janine 'Smurf' Cody'}    0
20                         Crazy Heart {'Bad Blake'}    1
21                    Up in the Air {'Ryan Bingham'}    0
22                           A Single Man {'George'}    0
23                       Invictus {'Nelson Mandela'}    0
24  The Hurt Locker {'Staff Sergeant William James'}    0

,Year,Category,Nominee,Additional Info,Won
0,2010,Actor -- Leading Role,Javier Bardem,Biutiful {'Uxbal'},0
1,2010,Actor -- Leading Role,Jeff Bridges,True Grit {'Rooster Cogburn'},0
2,2010,Actor -- Leading Role,Jesse Eisenberg,The Social Network {'Mark Zuckerberg'},0
3,2010,Actor -- Leading Role,Colin Firth,The King's Speech {'King George VI'},1
4,2010,Actor -- Leading Role,James Franco,127 Hours {'Aron Ralston'},0

In [107]:
additional_info_one = final_nominations['Additional Info'].str.rstrip("'}")
print('additional_info_one:')
print(additional_info_one.head())
additional_info_two = additional_info_one.str.split(" {'")
print('additional_info_two:')
print(additional_info_two.head())
movie_names = additional_info_two.str[0]
characters = additional_info_two.str[1]
print('movie_names:')
print(movie_names.head())
print('characters:')
print(characters.head())

additional_info_one:
0                        Biutiful {'Uxbal
1             True Grit {'Rooster Cogburn
2    The Social Network {'Mark Zuckerberg
3      The King's Speech {'King George VI
4                127 Hours {'Aron Ralston
Name: Additional Info, dtype: object
additional_info_two:
0                        [Biutiful, Uxbal]
1             [True Grit, Rooster Cogburn]
2    [The Social Network, Mark Zuckerberg]
3      [The King's Speech, King George VI]
4                [127 Hours, Aron Ralston]
Name: Additional Info, dtype: object
movie_names:
0              Biutiful
1             True Grit
2    The Social Network
3     The King's Speech
4             127 Hours
Name: Additional Info, dtype: object
characters:
0              Uxbal
1    Rooster Cogburn
2    Mark Zuckerberg
3     King George VI
4       Aron Ralston
Name: Additional Info, dtype: object

In [108]:
final_nominations['Movie'] = movie_names
final_nominations['Character'] = characters
final_nominations.head()

,Year,Category,Nominee,Additional Info,Won,Movie,Character
0,2010,Actor -- Leading Role,Javier Bardem,Biutiful {'Uxbal'},0,Biutiful,Uxbal
1,2010,Actor -- Leading Role,Jeff Bridges,True Grit {'Rooster Cogburn'},0,True Grit,Rooster Cogburn
2,2010,Actor -- Leading Role,Jesse Eisenberg,The Social Network {'Mark Zuckerberg'},0,The Social Network,Mark Zuckerberg
3,2010,Actor -- Leading Role,Colin Firth,The King's Speech {'King George VI'},1,The King's Speech,King George VI
4,2010,Actor -- Leading Role,James Franco,127 Hours {'Aron Ralston'},0,127 Hours,Aron Ralston

In [109]:
final_nominations = final_nominations.drop('Additional Info', axis=1)
final_nominations.head()

,Year,Category,Nominee,Won,Movie,Character
0,2010,Actor -- Leading Role,Javier Bardem,0,Biutiful,Uxbal
1,2010,Actor -- Leading Role,Jeff Bridges,0,True Grit,Rooster Cogburn
2,2010,Actor -- Leading Role,Jesse Eisenberg,0,The Social Network,Mark Zuckerberg
3,2010,Actor -- Leading Role,Colin Firth,1,The King's Speech,King George VI
4,2010,Actor -- Leading Role,James Franco,0,127 Hours,Aron Ralston

In [110]:
final_nominations.dtypes

Year          int64
Category     object
Nominee      object
Won           int64
Movie        object
Character    object
dtype: object

In [121]:
# move the table into a database
import sqlite3
# connecting to a non-existent path will create a new db
conn = sqlite3.connect('nominations.db')

# final_nominations.to_sql('nominations', conn, index=False)

query = 'pragma table_info(nominations)'
print('table schema:')
print(conn.execute(query).fetchall())
query = 'SELECT * FROM nominations LIMIT 10;'
print('\n')
print('first 10 rows:')
print(conn.execute(query).fetchall())

conn.close()

table schema:
[(0, 'Year', 'INTEGER', 0, None, 0), (1, 'Category', 'TEXT', 0, None, 0), (2, 'Nominee', 'TEXT', 0, None, 0), (3, 'Won', 'INTEGER', 0, None, 0), (4, 'Movie', 'TEXT', 0, None, 0), (5, 'Character', 'TEXT', 0, None, 0)]


first 10 rows:
[(2010, 'Actor -- Leading Role', 'Javier Bardem', 0, 'Biutiful', 'Uxbal'), (2010, 'Actor -- Leading Role', 'Jeff Bridges', 0, 'True Grit', 'Rooster Cogburn'), (2010, 'Actor -- Leading Role', 'Jesse Eisenberg', 0, 'The Social Network', 'Mark Zuckerberg'), (2010, 'Actor -- Leading Role', 'Colin Firth', 1, "The King's Speech", 'King George VI'), (2010, 'Actor -- Leading Role', 'James Franco', 0, '127 Hours', 'Aron Ralston'), (2010, 'Actor -- Supporting Role', 'Christian Bale', 1, 'The Fighter', 'Dicky Eklund'), (2010, 'Actor -- Supporting Role', 'John Hawkes', 0, "Winter's Bone", 'Teardrop'), (2010, 'Actor -- Supporting Role', 'Jeremy Renner', 0, 'The Town', 'James Coughlin'), (2010, 'Actor -- Supporting Role', 'Mark Ruffalo', 0, 'The Kids Are All Right', 'Paul'), (2010, 'Actor -- Supporting Role', 'Geoffrey Rush', 0, "The King's Speech", 'Lionel Logue')]